name: Backend Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Build and Test Backend

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
                
      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Make the Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x backend/gradlew

      # Step 4: Run Gradle tests
      - name: Run Gradle tests
        run: |
          cd backend
          ./gradlew clean test

      # Step 5: Upload test results 
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/build/test-results/test

      # Step 6: Upload XML test results
      - name: Convert JUnit XML to HTML
        run: |
          npm install -g htmlize-junit
          htmlize-junit -i '**/target/surefire-reports/TEST-*.xml' -o test-report.html
            
      # Step 7: Upload HTML test reports
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: test-report.html