name: Backend Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Build and Test Backend

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
                
      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Make the Gradle wrapper executable
      - name: Make gradlew executable
        run: chmod +x backend/gradlew

      # Step 4: Run Gradle tests
      - name: Run Gradle tests
        run: |
          cd backend
          ./gradlew clean test

      # Step 5: Upload test results 
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/build/test-results/test

      # Step 6: Upload XML test results
      - name: Generate HTML test reports
        if: always()
        run: |
          cd backend
          ./gradlew testReport || true
            
      # Step 7: Upload HTML test reports
      - name: Upload HTML test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-html
          path: backend/build/reports/tests/test

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> backend/.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> backend/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env

      # Step 5: Build backend
      - name: Build backend
        run: |
          cd backend
          ./gradlew build

      - name: Upload built backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend/build/libs/*.jar

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 7: Docker build and push
      - name: Docker build and push backend
        run: |
          pwd
          docker build -t guokecheng/molymarket:backend ./backend
          docker push guokecheng/molymarket:backend

      
      
